### Passo A: Criar a Conta de Luz "Em Aberto" (Não mexe no saldo)
POST http://localhost:8080/api/lancamentos
Content-Type: application/json

{
  "descricao": "Conta de Luz de Outubro",
  "valor": 150.00,
  "tipoLancamento": "DESPESA",
  "dataVencimento": "2026-10-20",
  "pago": false,
  "usuario": { "id": 1 },
  "conta": { "id": 1 },
  "categoria": { "id": 2 }
}

### Passo B: Efetuar a Baixa da Conta de Luz criada (Deve ser o ID 3 se o H2 reiniciou zerado)
PUT http://localhost:8080/api/lancamentos/1/baixar