# Nome do nosso sistema
spring.application.name=financeiro_api

# Conexão com o Banco de Dados H2 em Memória
spring.datasource.url=jdbc:h2:mem:financadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativação do painel visual do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Hibernate/JPA para criar as tabelas sozinhos
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true